spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    view-names: thymeleaf/*

server:
  error:
    include-stacktrace: on_param
    include-message: on_param
    include-exception: off
    include-binding-errors: on_param